import React, { useEffect, useState, useCallback } from "react";
import { reviewService } from "../../services/reviewService.js";
import { SparklesIcon, AlertCircleIcon, RefreshIcon } from "../common/Icons.jsx";

/**
 * AI Review Summary Component
 * Displays a grounded, qualitative review summary generated by LLM from approved customer reviews.
 * Kept visually distinct from original customer reviews with clear AI-generated transparency labelling.
 * Deterministic rating metrics (e.g., average rating, 1-5 star breakdown) remain separate.
 */
export default function AIReviewSummary({ productId }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchSummary = useCallback(async () => {
    if (!productId) return;
    try {
      setLoading(true);
      setError(null);
      const res = await reviewService.getAIReviewSummary(productId);
      if (res && res.success) {
        setData(res.data);
      } else {
        setData(null);
      }
    } catch (err) {
      console.warn("[AIReviewSummary] Failed to load review summary:", err.message);
      setError(
        err.response?.data?.message ||
          "AI review summary is temporarily unavailable. Original reviews remain accessible."
      );
    } finally {
      setLoading(false);
    }
  }, [productId]);

  useEffect(() => {
    fetchSummary();
  }, [fetchSummary]);

  // 1. Loading State (Gleaming skeleton)
  if (loading) {
    return (
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-slate-900/90 via-slate-900/60 to-indigo-950/30 border border-indigo-500/20 p-6 shadow-xl backdrop-blur-md animate-pulse space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-5 h-5 rounded-full bg-indigo-500/30" />
            <div className="w-36 h-4 bg-slate-800 rounded-md" />
          </div>
          <div className="w-24 h-5 bg-slate-800 rounded-full" />
        </div>
        <div className="space-y-2 pt-1">
          <div className="w-full h-3.5 bg-slate-800 rounded" />
          <div className="w-5/6 h-3.5 bg-slate-800 rounded" />
          <div className="w-2/3 h-3.5 bg-slate-800 rounded" />
        </div>
        <div className="flex gap-2 pt-2">
          <div className="w-20 h-6 bg-slate-800 rounded-lg" />
          <div className="w-24 h-6 bg-slate-800 rounded-lg" />
          <div className="w-16 h-6 bg-slate-800 rounded-lg" />
        </div>
      </div>
    );
  }

  // 2. Error State (Non-blocking with retry button)
  if (error) {
    return (
      <div className="rounded-2xl bg-slate-900/40 border border-slate-800/80 p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3 text-slate-400 text-xs">
          <AlertCircleIcon className="w-5 h-5 text-amber-400 flex-shrink-0" />
          <span>{error}</span>
        </div>
        <button
          type="button"
          onClick={fetchSummary}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition border border-slate-700/60"
        >
          <RefreshIcon className="w-3.5 h-3.5" />
          <span>Retry</span>
        </button>
      </div>
    );
  }

  // 3. Insufficient / Zero Reviews State
  if (!data || !data.summary || data.reviewCount === 0) {
    return (
      <div className="rounded-2xl bg-gradient-to-br from-slate-900/70 to-slate-950/80 border border-slate-800/80 p-6 text-center space-y-2">
        <div className="inline-flex items-center justify-center w-9 h-9 rounded-xl bg-indigo-500/10 text-indigo-400 mb-1 border border-indigo-500/20">
          <SparklesIcon className="w-5 h-5" />
        </div>
        <h4 className="text-sm font-bold text-slate-300">AI Review Summary</h4>
        <p className="text-xs text-slate-400 max-w-md mx-auto">
          {data?.message || "There are not enough approved reviews yet to generate an AI summary."}
        </p>
      </div>
    );
  }

  const { summary, sentiment = "positive", themes = [], reviewCount = 0 } = data;

  // Sentiment badge styling
  const sentimentConfig = {
    positive: {
      label: "Positive Sentiment",
      badgeClass: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30",
      dotClass: "bg-emerald-400"
    },
    mixed: {
      label: "Mixed Sentiment",
      badgeClass: "bg-amber-500/15 text-amber-300 border-amber-500/30",
      dotClass: "bg-amber-400"
    },
    negative: {
      label: "Critical Sentiment",
      badgeClass: "bg-rose-500/15 text-rose-300 border-rose-500/30",
      dotClass: "bg-rose-400"
    }
  };

  const currentSentiment = sentimentConfig[sentiment] || sentimentConfig.mixed;

  // Theme sentiment badge styling
  const getThemeSentimentClass = (themeSent) => {
    if (themeSent === "positive") {
      return "bg-emerald-500/10 text-emerald-300 border-emerald-500/20";
    }
    if (themeSent === "negative") {
      return "bg-rose-500/10 text-rose-300 border-rose-500/20";
    }
    return "bg-amber-500/10 text-amber-300 border-amber-500/20";
  };

  return (
    <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-slate-900/90 via-slate-900/70 to-indigo-950/40 border border-indigo-500/30 p-6 sm:p-7 shadow-2xl backdrop-blur-lg space-y-5 transition-all duration-300 hover:border-indigo-500/40">
      {/* Subtle glowing ambient accent */}
      <div className="absolute -top-16 -right-16 w-36 h-36 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />

      {/* Header Row: Title, AI Sparkle, Sentiment, Review Count */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800/80 pb-4">
        <div className="flex items-center gap-2.5">
          <div className="flex items-center justify-center w-8 h-8 rounded-xl bg-gradient-to-tr from-indigo-600 to-cyan-500 text-white shadow-md shadow-indigo-500/20">
            <SparklesIcon className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-bold text-white tracking-tight">
                AI Review Summary
              </h3>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                AI Intelligence
              </span>
            </div>
            <p className="text-[11px] text-slate-400">
              Based on {reviewCount} approved customer {reviewCount === 1 ? "review" : "reviews"}
            </p>
          </div>
        </div>

        {/* Overall Sentiment Badge */}
        <div
          className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold border ${currentSentiment.badgeClass}`}
        >
          <span className={`w-1.5 h-1.5 rounded-full ${currentSentiment.dotClass}`} />
          <span>{currentSentiment.label}</span>
        </div>
      </div>

      {/* Qualitative Summary Narrative */}
      <p className="text-sm sm:text-base text-slate-200 leading-relaxed font-normal">
        {summary}
      </p>

      {/* Themes Breakdown */}
      {themes.length > 0 && (
        <div className="space-y-2.5 pt-1">
          <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
            Common Themes Identified
          </h4>
          <div className="flex flex-wrap gap-2">
            {themes.map((theme, idx) => (
              <div
                key={idx}
                className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-medium border ${getThemeSentimentClass(
                  theme.sentiment
                )}`}
              >
                <span className="font-semibold">{theme.name}</span>
                <span className="text-[10px] uppercase font-bold tracking-wider opacity-80 capitalize">
                  • {theme.sentiment}
                </span>
                {theme.evidenceCount !== undefined && theme.evidenceCount > 0 && (
                  <span className="text-[10px] opacity-60 font-mono">
                    ({theme.evidenceCount})
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* AI Transparency & Disclaimer Footer */}
      <div className="pt-3 border-t border-slate-800/60 flex items-center justify-between text-[11px] text-slate-500">
        <span className="flex items-center gap-1.5">
          <span className="inline-block w-1.5 h-1.5 rounded-full bg-indigo-400" />
          AI-generated summary based exclusively on approved customer reviews.
        </span>
        <span className="hidden sm:inline text-slate-600">
          Source: MongoDB Verified Reviews
        </span>
      </div>
    </div>
  );
}
